# Welcome to Jekyll!
#

# Site settings
title: Chisomo Lungu
description: |
  Full Stack Web Developer |
  Chess player and tech enthusiast
owner: chisomo lungu # or company name

email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chisomolungu.co.uk" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/chisomo16
  github: https://github.com/obfusticatedcode
  linkedin-square: https://www.linkedin.com/in/chisomo-lungu-6a8a05a0/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
